fix: inject button in the proper place
phantombuster/web-browser-extension pull request #23
Opened 2022-06-09 16:35 UTC by RiahiKarim

## 📝 What is this PR

[FE-106](https://phantombuster.atlassian.net/jira/software/projects/FE/boards/46?selectedIssue=FE-106)
> The web extension doesn’t inject the “Connect to service“ button in the proper place. This is because the input DOM node selector changed after rebranding the setup page.
> 
![image](https://user-images.githubusercontent.com/12436800/172897543-36b4b969-55fb-422f-8c69-d9ed91d3c7ae.png)

## ⚠️  Note
The web extension is working now the deploy previews domains. We absolutely need that to test th extension properly.

## 🧪 How to test

### First, build and load the extension into your browser

- run `nvm use` on the parent folder of the web extension
- run `npm i`
- run `npm run build`
- Follow [these steps](https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked) to load an unpacked extension into chrome.
- Follow [these steps](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing) to load the extension into firefox.

### Testing the extension
- Check the new icon of the extension
- Go to a deploy preview (rebranded website), use different scripts (twitter, facebook, linkedin ...), and check the new styling of the `Connect to {service}` button.
- Check that the extension is still working properly.

![twitter extension](https://user-images.githubusercontent.com/12436800/172898793-ca4450f1-f09c-4f56-981a-31e4255accfc.gif)

2022-06-10 09:14 UTC, Oxygen66 requested changes
Small request 👍  Rest LGTM

2022-06-13 06:43 UTC, Hatscat commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +	private _stepSetupSessionCookieInnerDivSelector = "div + div"
I agree with you @Oxygen66, for all other selectors too, it's not better:
```ts
private _stepSetupSessionCookieInputSelector = "input"
private _getCookieButtonClass = "pbExtensionNewSetupCookieButton"
private _phantomNameSelector1 = "header p"
private _phantomNameSelector2 = "aside header span"
```

but I suggest to delay this improvement for after the rebranding, because the two extensions (the current one and the rebranded one) should be compatible with the 2 PB apps (current and rebranded), because some users will not update their extensions and we may need to rollback the application if something goes wrong and the rebranded extension will be available. WDYT?

2022-06-13 07:28 UTC, RiahiKarim commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +	private _stepSetupSessionCookieInnerDivSelector = "div + div"
@Oxygen66 We can improve the web extension selectors by using unique identifiers but I don't think that right now is the best moment to do it. No one from the Platform/Front team is very familiar with the web extension's code and we could break it while trying to improve it...

> The two extensions (the current one and the rebranded one) should be compatible with the 2 PB apps (current and rebranded)
That's not the case currently @Hatscat. The 2 apps have different DOM elements. The old extension will not work on the rebranded website. The rebranded extension will not work on the old website.

2022-06-13 08:16 UTC, RiahiKarim commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +	private _stepSetupSessionCookieInnerDivSelector = "div + div"
It doesn't work. The button is not injected.

Old website + rebranded extension.

![image](https://user-images.githubusercontent.com/12436800/173309872-c859b48e-c0a1-4d95-94e4-4d749a34b905.png)

2022-06-13 09:29 UTC, stressGC commented on manifest.json
> +				"*://*.phantomcompany.io/*"
Won't this display a new "allow extension to access domain" popup to users? If so, we shouldn't do it

2022-06-13 09:29 UTC, stressGC commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +	private _stepSetupSessionCookieInnerDivSelector = "div + div"
@RiahiKarim this is a big issue, we should have a two ways compatibility

2022-06-13 09:30 UTC, stressGC requested changes
See ongoing discussions

2022-06-13 15:01 UTC, closed without merging

2022-06-13 15:02 UTC, RiahiKarim commented
The proposed solution doesn't allow the users that don't upgrade their web extension to use it with rebranded website version.