docs(README): add warning about manifest update risk
phantombuster/web-browser-extension pull request #33
Opened 2022-08-04 15:26 UTC by Hatscat

[Specs](https://phantombuster.atlassian.net/browse/CP-185)

2022-08-09 08:53 UTC, RiahiKarim reviewed
nit

2022-08-09 08:53 UTC, RiahiKarim commented on README.md
> +Please be very careful when updating Manifest fields values like adding an entry in `permissions` or in `content_scripts.matches`, it may impact users by disabling the extension and requiring to acce
```suggestion
Please be very careful while updating the values of the manifest fields such as adding a new entry in `permissions` or in `content_scripts.matches`. it may impact our users by disabling the extension and requiring them to accept new authorizations. It already occurred twice by mistake for this extension.
```

2022-08-10 12:59 UTC, Oxygen66 submitted a review, later dismissed
LGTM 👍 Just solve Karim's suggestion

2022-08-16 07:00 UTC, Hatscat commented on README.md
> +Please be very careful when updating Manifest fields values like adding an entry in `permissions` or in `content_scripts.matches`, it may impact users by disabling the extension and requiring to acce
thank yo @RiahiKarim  ^^

2022-08-16 07:28 UTC, RiahiKarim approved these changes
LGTM 💯

2022-08-22 13:30 UTC, Oxygen66 requested changes
LGTM 👍

2022-08-22 13:30 UTC, Oxygen66 approved these changes

2022-08-22 13:30 UTC, merged