Cp 186 add sentry
phantombuster/web-browser-extension pull request #38
Opened 2022-08-30 08:43 UTC by Hatscat

* [Specs](https://phantombuster.atlassian.net/browse/CP-186)

## Notes

* it's not possible to track when the extension is disable ([a new "management" permission is require and "An extension on its own can't monitor when it gets disabled. You'd need a second extension to monitor this"](https://stackoverflow.com/questions/13979781/chrome-extension-how-to-handle-disable-and-enable-event-from-browser))

2022-09-01 07:42 UTC, RiahiKarim commented on tsconfig.json
> +		"sourceMap": true,
Is there a reason behind this change or is it just for debugging purposes?

2022-09-01 07:47 UTC, Hatscat commented on tsconfig.json
> +		"sourceMap": true,
it's to produce sourcemaps for sentry debugging purpose

2022-09-01 07:51 UTC, RiahiKarim commented on tsconfig.json
> +		"sourceMap": true,
Are the content script and the background script still obfuscated when you install the web extension?

2022-09-01 09:53 UTC, Hatscat commented on tsconfig.json
> +		"sourceMap": true,
sources maps are now separated files that does not impact the script, before that the webpack config was embedding the source maps inside the script ("inline source maps"), but it was not readable by Sentry.
and I don't think that the script should be obfuscated: this is a public repository, the source code is freely accessible to everyone

2022-09-07 06:49 UTC, RiahiKarim commented on manifest.json
> +	"content_security_policy": "script-src 'self' https://browser.sentry-cdn.com; object-src 'self'",
I don't think this is required since we don't load sentry from the cdn `https://browser.sentry-cdn.com`. Sentry was added as a node module and therefore should be in the final bundle.

2022-09-07 06:56 UTC, RiahiKarim commented on package.json
> +		"build:beta": "cpy dist/*.js dist/*.css dist/*.map beta && jq -s '.[0] * .[1]' dist/manifest.json manifest.beta.json > beta/manifest.json",
The source map files are relevant for our users. The final zip file is around 320KB while it was around 100KB without the source map files.

How about adding a new npm script (i.e `build:srentry` or `release:sentry`) that generates the source maps?

2022-09-07 07:02 UTC, RiahiKarim commented on src/background/background.ts
> +	wrapAsyncFunctionWithSentry(async () => {
This extension manages to use `Sentry.wrap` in their [background.js](https://github.com/hirosystems/stacks-wallet-web/blob/b46a97d178522b751bee8f54a954567e53c919e7/src/background/background.ts#L31) script. What's preventing us from doing the same?

2022-09-07 07:26 UTC, Hatscat commented on package.json
> +		"build:beta": "cpy dist/*.js dist/*.css dist/*.map beta && jq -s '.[0] * .[1]' dist/manifest.json manifest.beta.json > beta/manifest.json",
ok, i added a dedicated build:dev

2022-09-07 07:39 UTC, Hatscat commented on src/background/background.ts
> +	wrapAsyncFunctionWithSentry(async () => {
it require an additional function scope over the Sentry.wrap, so I find his behavior unexpected IMO, and it do not handle runtime errors which are specific to extensions like our helper do with `captureRuntimeErrorIfAny`

and I feel that we are not missing much by not using it:
```ts
/**
 * Wrap code within a try/catch block so the SDK is able to capture errors.
 *
 * @param fn A function to wrap.
 *
 * @returns The result of wrapped function call.
 */
export declare function wrap(fn: (...args: any) => any): any;
```

2022-09-07 09:53 UTC, RiahiKarim commented on src/background/background.ts
> +	wrapAsyncFunctionWithSentry(async () => {
Alright

2022-09-07 09:53 UTC, RiahiKarim approved these changes
LGTM 💯

2022-09-07 10:05 UTC, Oxygen66 requested changes
LGTM, just few nit 👍

2022-09-07 12:19 UTC, RiahiKarim approved these changes
LGTM 💯

2022-09-07 12:22 UTC, Oxygen66 approved these changes
LGTM 👍

2022-09-07 12:25 UTC, merged