chore(sentry): Ignore errors and fix source map
phantombuster/web-browser-extension pull request #50
Opened 2022-10-20 07:46 UTC by LoganPB

## 📝 What is this PR

This PR fixes the source map generation for Sentry.
It ignores two errors that are spamming Sentry.
Upgrade the SDK of the Sentry Javascript library.

-   [Specs](https://phantombuster.atlassian.net/browse/CP-266)

## 🏭 How does it work

On the sentry-release.yml, there was an error, and the wrong build was done.
To ignore the message, Sentry.init has a parameter "ignoreErrors", so I added the two errors two filters.

## 🗒 Notes

**Something you need to inform your reviewers about**

-   [ ] This change requires a documentation update
-   [ ] This change requires a unit tests update

## 🧪 QA Process

**Details a QA process to the reviewers**

### ✅ Positive testing (should succeed)

-   When the release will be done, we have to check if the source maps are correctly uploaded on Sentry and if the logs don't appear again.

## 👌 To check

-   [ ] There's no regression
-   [ ] Coding guidelines are followed ([Contributing](https://github.com/phantombuster/engineering-docs/blob/master/contributing.md), [Testing](https://github.com/phantombuster/engineering-docs/blob/master/testing.md))

2022-10-20 08:09 UTC, Oxygen66 requested changes

2022-10-20 08:09 UTC, Oxygen66 commented on src/shared/sentry.ts
> +		ignoreErrors: ["Non-Error exception captured", "ResizeObserver loop limit exceeded"],
Can you document this line please ?

2022-10-20 08:28 UTC, RiahiKarim submitted a review, later dismissed
LGTM 💯 .

It seems that `ResizeObserver - loop limit exceeded` errors can be [safely ignored](https://stackoverflow.com/a/50387233) but I am not sure about the [Non-Error Exception events ](https://docs.sentry.io/platforms/javascript/troubleshooting/#events-with-non-error-exception), we might be doing something wrong.

In any case, I think it is a good idea to merge your PR to ignore these two errors and maybe look further for the Non-Error Exception events.

2022-10-20 15:39 UTC, Hatscat approved these changes
LGTM

2022-10-24 13:48 UTC, RiahiKarim approved these changes
LGTM

2022-10-25 13:38 UTC, Oxygen66 approved these changes
LGTM 👍

2022-10-25 13:38 UTC, merged