Chore(manifest): update manifest v3
phantombuster/web-browser-extension pull request #51
Opened 2022-10-20 14:50 UTC by LoganPB

## 📝 What is this PR

This PR updates the version of the manifest to upgrade from V2 to V3. The new version is required by Google Chrome starting next year.

-   [Specs](https://phantombuster.atlassian.net/browse/CP-220)

## 🏭 How does it work

Google has a guide to migrate from V2 to V3 [https://developer.chrome.com/docs/extensions/mv3/mv3-migration/](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/). The manifest and some files of the code has been updated. There's also the change from "webextension-polyfill-ts" to "@types/webextension-polyfill" because the first one is deprecated now.

## 🗒 Notes
This version is not functional on Firefox at the moment. Firefox should support Manifest V3 at the end of the year "normally".

## 🧪 QA Process

To test the extension :

npm i
npm run clean
npm run build:dev
On Google Chrome, open chrome://extensions/
Enable the Developer mode
Click on Load Unpacked
Select the dev-build folder
The extension should be activated in the browser (don't forget to disable the official extension)

### ✅ Positive testing (should succeed)

-  To test the update :

**Test when the user is already connected to the service:**
- Use a phantom
- Click on the "Connect to XXXX" button to get the cookie
- The phantom should work

**Test when the user is not connected to the service:**
- Use a phantom
- Click on the "Connect to XXXX" button. You should have a new tab opened
- Log in
- You are redirected to the PhantomBuster page

**Test to click the "Connect to XXXX" with Shift pushed**
- Use a phantom
- Click on the "Connect to XXXX" button with Shift pushed
- Nothing should change

## 👌 To check

-   [ ] There's no regression
-   [ ] Coding guidelines are followed ([Contributing](https://github.com/phantombuster/engineering-docs/blob/master/contributing.md), [Testing](https://github.com/phantombuster/engineering-docs/blob/master/testing.md))

2022-10-20 15:48 UTC, Hatscat commented
> ## ⚠️ The Manifest was updated! Be very careful about this! ([more infos here](https://github.com/phantombuster/web-browser-extension#%EF%B8%8F-manifest-update-warning))
> ```diff
> 2c2
> < 	"manifest_version": 3,
> ---
> > 	"manifest_version": 2,
> 13c13
> < 		"service_worker": "background.js"
> ---
> > 		"scripts": ["background.js"]
> 15c15
> < 	"action": {
> ---
> > 	"browser_action": {
> 28,29c28,31
> < 	"permissions": ["notifications", "tabs", "cookies"],
> < 	"host_permissions": [
> ---
> > 	"permissions": [
> > 		"notifications",
> > 		"tabs",
> > 		"cookies",
> 46,51c48
> < 	"web_accessible_resources": [
> < 		{
> < 			"resources": ["assets/*"],
> < 			"matches": ["<all_urls>"]
> < 		}
> < 	]
> ---
> > 	"web_accessible_resources": ["assets/*"]
> ```

I have the impression that the diff is reversed ^^"

2022-10-24 08:08 UTC, Hatscat requested changes
it works well for me 🙂

2022-10-24 08:08 UTC, Hatscat commented on package.json
> +		"@types/webextension-polyfill": "^0.9.1",
I think you forgot to commit the lock file, there are some diffs inside it when running `npm i`:
![image](https://user-images.githubusercontent.com/3329016/197477183-a83ce8e0-b1e9-42e5-a1e0-7b7434870cb9.png)

2022-10-24 08:08 UTC, Hatscat commented on manifest.json
>  	"version": "1.1.6.8",
plz bump the version, at least a patch I think (so you have to update `beta-updates.json`, `manifest.beta.json` and `package.json` files too
```suggestion
	"version": "1.1.7.0",
```

2022-10-24 12:07 UTC, LoganPB commented on package.json
> +		"@types/webextension-polyfill": "^0.9.1",
Fixed 👍

2022-10-24 12:31 UTC, Hatscat approved these changes
LGTM, GG 👍

2022-10-24 14:13 UTC, RiahiKarim reviewed
Great job @LoganPB. Thank you for the detailed QA process.

Code LGTM 💯 .

The idea of having a code base on the main branch that doesn't build on firefox makes me uneasy, maybe we should create a `epic/manifest-v3` branch for now and wait for firefox to fully support manifest v3.

@Hatscat WDYT?

2022-10-24 14:16 UTC, Hatscat commented
> Great job @LoganPB. Thank you for the detailed QA process.
> 
> Code LGTM 💯 .
> 
> The idea of having a code base on the main branch that doesn't build on firefox makes me uneasy, maybe we should create a `epic/manifest-v3` branch for now and wait for firefox to fully support manifest v3.
> 
> @Hatscat WDYT?

yes good idea @RiahiKarim! we still could deploy from the epic, the only thing to think is to manually create sentry release because it's done at CI time when merging in beta

2022-10-25 08:50 UTC, LoganPB commented on src/shared/inject.ts
>  export const injectJsFile = (fileName: string) => {
Fixed 👍

2022-10-25 12:04 UTC, RiahiKarim approved these changes
LGTM 💯

2022-10-25 13:37 UTC, merged