feat: collect additional LinkedIn user info
phantombuster/web-browser-extension pull request #84
Opened 2023-09-12 09:29 UTC by val92130

## 📝 What is this PR

This PR aims to serve as a "proof of concept" to see if it's possible to easily retrieve additional LinkedIn user data directly from the extension.

## 🏭 How does it work

LinkedIn's data is retrieved using the LinkedIn's web API, specifically the `mysettings-api/settingsApiMiniProfile` endpoint.

The flow of the code is:
- When LinkedIn cookies are retrieved in the background process we use those cookies to find the CSRF token
- When the CSRF token is found, a request to the  `mysettings-api/settingsApiMiniProfile` endpoint is made
- The response is then validated and forwarded to the content script (phantombusterNewSetup.ts)
- The content script then sends back the user info to the PhantomBuster's React app using `window.dispatchEvent`
- The React app can then intercept this event using `window.addEventListener("PB_EXTENSION_MESSAGE", callback)`

## 🗒 Notes

This new feature introduces the use of LinkedIn's API. This can be potentially "unsafe" as it could be detected by LinkedIn if they start doing extensive security checks. It might be a good idea to introduce this feature to a subset of users at first (or only internally).

## 🧪 QA Process

- Build the extension locally & install it in your browser
- Open the Chrome extensions panel: chrome://extensions/
- Find the PhantomBuster DEV extension and click to open the "service worker"
- Go to a LinkedIn's Phantom setup on your local front environment and click "connect to linkedin"
- Make sure cookies are filled correctly like before
- Check the "service worker" window. The console should display a log with `Received LinkedIn user info`

You can also edit your frontend app locally and add the following code in FormInput/Text.tsx:
```typescript
	useEffect(() => {
		const handleExtensionMessage = (event: CustomEvent) => {
			if (event.type === "PB_EXTENSION_MESSAGE") {
				console.log("RECEIVED", event.detail)
			}
		}

		window.addEventListener("PB_EXTENSION_MESSAGE", handleExtensionMessage as EventListener)
		return () => window.removeEventListener("PB_EXTENSION_MESSAGE", handleExtensionMessage as EventListener)
	}, [])
```

## 👌 To check

-   [ ] There's no regression
-   [ ] Coding guidelines are followed ([Contributing](https://github.com/phantombuster/engineering-docs/blob/master/contributing.md), [Testing](https://github.com/phantombuster/engineering-docs/blob/master/testing.md))

2023-09-12 10:11 UTC, GabrielCousin reviewed
🔥

2023-09-12 10:17 UTC, GabrielCousin commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +		const event = new CustomEvent("PB_EXTENSION_MESSAGE", {
Posting it there so we could have it somewhere in mind - I don't know that's something to try out or it could help to save things locally (maybe it could prevent us from exceeding rate limits)
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local
But we might be careful if it would have some impact on extension permissions

2023-09-12 12:04 UTC, val92130 commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +		const event = new CustomEvent("PB_EXTENSION_MESSAGE", {
> Posting it there so we could have it somewhere in mind - I don't know that's something to try out or it could help to save things locally (maybe it could prevent us from exceeding rate limits) https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local But we might be careful if it would have some impact on extension permissions

for sure! I think the end goal though is to save the data on the frontend side (maybe agent object) so we would not have to call the API everytime

2023-09-15 07:25 UTC, GabrielCousin commented on src/background/background.ts
> +	const csrfToken = cookies.find((cookie) => cookie.name === "JSESSIONID")?.value?.replace(/"/g, "")
Could we leave some explanation for the string replacement? or is it because the value is a string wrapped with extra db-quotes?

2023-09-15 07:39 UTC, GabrielCousin approved these changes

2023-09-19 07:37 UTC, val92130 commented on src/background/background.ts
> +	const csrfToken = cookies.find((cookie) => cookie.name === "JSESSIONID")?.value?.replace(/"/g, "")
> Could we leave some explanation for the string replacement? or is it because the value is a string wrapped with extra db-quotes?

exactly! I added a comment, lmk if it's clear enough

2023-09-19 08:09 UTC, GabrielCousin approved these changes

2023-09-19 15:20 UTC, RiahiKarim requested changes
I have one small comment please

2023-09-19 15:33 UTC, val92130 commented on src/background/background.ts
> +	const profileInfo = await getProfileInfo({
> I would wrap this method in a try/catch. It will keep the web extension functioning when the fetch logic fails
> 
> ```ts
> const fetchLinkedinUserInfo = async (tabId: number, csrfToken: string, cookieName: string) => {
> 	let profileInfo: IUserInfo  | undefined
> 	try {
> 		profileInfo = await getProfileInfo({ csrfToken })
> 	} catch (error) {
> 		// You call Val: Do nothing or Send an exception to Sentry
> 	}
> 
> 	return sendMessage(tabId, {
> 		userInfo: {
> 			info: profileInfo,
> 			websiteName: "LinkedIn",
> 			cookieName,
> 		},
> 	})
> }
> ```
> 
the errors are already handled because the top method is wrapped with `wrapAsyncFunctionWithSentry`.
I tried to make the request fail on purpose and it didn't break the extension and it created an entry on Sentry: https://phantombuster.sentry.io/issues/4489200528/?project=6698508&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

> note: The imageUrl mapping logic can go inside linkedin.ts/getProfileInfo

I chose to make it so that `getProfileInfo` does not perform any transformation on the data and rather returns the raw data from linkedin. Do you want me to make the change still?

2023-09-19 15:40 UTC, RiahiKarim commented on src/background/background.ts
> +	const profileInfo = await getProfileInfo({
> I tried to make the request fail on purpose and it didn't break the extension and it created an entry on Sentry: https://phantombuster.sentry.io/issues/4489200528/?project=6698508&query=is%3Aunresolved&referrer=issue-stream&stream_index=1
Thank you for checking 👌

> I chose to make it so that getProfileInfo does not perform any transformation on the data and rather returns the raw data from linkedin. Do you want me to make the change still?
Nah, it is okay ^^

2023-09-19 15:41 UTC, RiahiKarim approved these changes
LGTM 💯 . Let's submit a new version of the web extension tomorrow 🎉

2023-09-19 19:04 UTC, val92130 commented
> @val92130 I tried to test on Firefox and it is not working.
> 
> Here is some context of what's happening:
> 
> The extension is triggering the LinkedIn API call to retrieve the user information without any issues:
> The front-end doesn't render the connected LinkedIn account and throws this error
> It seems that the event detail is Restricted and cannot be accessed
> ![image](https://user-images.githubusercontent.com/12436800/269031522-38a670c3-919c-4fda-9ba7-05a6dc20feff.png)
> 
> I found this [StackOverflow ](https://stackoverflow.com/a/46081249) thread. We can try out the `cloneInfo` method.

nice catch, thanks for the details!
I ended up using the `window.postMessage` method which works perfectly in both Chrome and Firefox. Let me know what you think 😄

2023-09-20 06:55 UTC, GabrielCousin commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +		window.postMessage(message, "*")
Posting this as a comment that doesn't expect any action - MDN docs are encouraging not to use a wildcard but in the meantime, I'm pretty sure we have to support many domain especially for the dev version

2023-09-20 06:55 UTC, GabrielCousin submitted a review, later dismissed

2023-09-20 06:58 UTC, GabrielCousin commented
@RiahiKarim @val92130 do you prefer bumping the version in a dedicated PR or in this one instead?

2023-09-20 07:04 UTC, RiahiKarim commented
> @RiahiKarim @val92130 do you prefer bumping the version in a dedicated PR or in this one instead?

Let's do it in a dedicated PR. @GabrielCousin are you familiar with the web extension release process (I am not)?

Val & I will try to release the web extension today. Your help would be appreciated.

2023-09-20 07:16 UTC, Senshii reviewed
🔥

2023-09-20 07:16 UTC, Senshii approved these changes

2023-09-20 08:48 UTC, val92130 commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +		window.postMessage(message, "*")
> Posting this as a comment that doesn't expect any action - MDN docs are encouraging not to use a wildcard but in the meantime, I'm pretty sure we have to support many domain especially for the dev version

I agree, maybe this could be improved though, I'm not really familiar with the "postMessage" function. Maybe we should only whitelist localhost and phantombuster.com?

2023-09-20 11:28 UTC, GabrielCousin approved these changes

2023-09-20 11:30 UTC, GabrielCousin commented on src/shared/linkedin.ts
> +	if (fetchResponse.status !== 200) {
Last question, shall we ignore `401`? I'm worried about the Sentry quota 😄

2023-09-20 11:46 UTC, GabrielCousin commented on src/contentscript/handlers/phantombusterNewSetup.ts
> +		window.postMessage(message, "*")
I feel it's only accepting one entry so we're kind of blocked - let's see this later on

2023-09-20 12:10 UTC, val92130 commented on src/shared/linkedin.ts
> +	if (fetchResponse.status !== 200) {
> Last question, shall we ignore `401`? I'm worried about the Sentry quota 😄

I think it's best to not ignore anything then we can make some tweaks later if we see some recurring errors on Sentry. What do you think?

2023-09-20 13:27 UTC, RiahiKarim approved these changes
LGTM 💯

2023-09-20 13:55 UTC, GabrielCousin commented on src/shared/linkedin.ts
> +	if (fetchResponse.status !== 200) {
👍

2023-09-20 13:57 UTC, merged